### ISSUE TITLE
老哥刷课有错误啊

### ISSUE THREAD

**Issue by zsjlovestudy** [lusao-xg/Mosoteach#1]
什么列表索引错误
![image](https://user-images.githubusercontent.com/52393677/69216463-3da6b180-0ba7-11ea-903c-6aeb1fd3867e.png)

菜鸡一枚看不懂。。
有几门课可以刷啊 有几门课不行

**Comment by ubadly** [comment]
报错的截图麻烦给我发一下

发自我的 iPhone

**Comment by ubadly** [comment]
源码是旧的，新的忘记更新了，你稍等我发布一下修改过的

发自我的 iPhone

**Comment by zsjlovestudy** [comment]
![QQ截图20191120180051](https://user-images.githubusercontent.com/52393677/69233474-ed8c1700-0bc7-11ea-9de6-e777a945fc58.png)什么列表超出索引


老哥，能改吗 我怕挂课，我们老师看经验给平常分，坑的很。

**Comment by ubadly** [comment]
发下你的QQ，我把文件发给你，我现在有点忙，就不想整理代码了

发送自 Windows 10 版邮件应用

发件人: zsjlovestudy
发送时间: 2019年11月20日 19:01
收件人: lusao-xg/Mosoteach
抄送: LuSao; Comment
主题: Re: [lusao-xg/Mosoteach] 老哥刷课有错误啊 (#1)

什么列表超出索引
老哥，能改吗 我怕挂课，我们老师看经验给平常分，坑的很。

**Comment by zsjlovestudy** [comment]
1195609423     感谢大佬！！！！！！！！
