### ISSUE TITLE
我体验了一下

### ISSUE THREAD

**Issue by tomlongcool** [lusao-xg/Mosoteach#3]
一会看看结果，老哥有联系方式吗

**Comment by ubadly** [comment]
上面的代码随着官网的更新已经失效了，新的我已经写出来了，不过没有更新，我今天看情况更新吧

发自我的iPhone

**Comment by tomlongcool** [comment]
谢谢您

**Comment by ubadly** [comment]
更新了

发自我的iPhone

**Comment by zsjlovestudy** [comment]
我又试了下  好像这个有bug，刷了一会自动停了，然再次执行脚本还是能刷，就是这样执行一次刷一次，一次刷十几个。

**Comment by ubadly** [comment]
不能吧  方便账号密码发一下吗

发自我的iPhone

**Comment by zsjlovestudy** [comment]
谢谢老哥，  资源现在还不多，被我刷完了，下次发你 我有你qq🤭

**Comment by ubadly** [comment]
哪个是你

发自我的iPhone
