### ISSUE TITLE
建议更新主分支中的requirements

### ISSUE THREAD

**Issue by EternalmBlue** [lusao-xg/Mosoteach#7]
快结课了，今天准备刷刷云班课积分。今年夏天用你写的程序发现使用简单且好用，今天再用发现报错，看了一下，urllib太新，request库太旧。把requirements.txt中的requests改成requests==2.32.3后程序正常运行。你的依赖机器人已经帮你改好了并建立了一个新分支，我是自己改好之后才发现的。但是也许你可以照顾一下那些没看到的朋友和刚用github的萌新...

**Comment by ubadly** [comment]
已解决
